# -*- coding: utf-8 -*-
"""telecom_churn_R.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gV0I6BWGk7GBpcQUQhRBhTP5HNbwI7l2

# Telecom Churn Model using Logistic Regression
A sample of 3333 active customers was randomly selected from the entire customer base from a US-owned telecommunications company. Based on earlier studies, the company found out that the customer demographic and socio-economic factors were not significant predictors of churn. So, this study focuses only on the ‘call related’ parameters, like call duration during various times of the day, number of cals, call costs and calls made to the call center etc.

Telecom companies have used two approaches to address churn - (a) Untargeted approach and **(b) Targeted approach. The untargeted approach relies on superior product and mass advertising to increase brand loyalty and thus retain customers. The targeted approach relies on identifying customers who are likely to churn, and provide suitable intervention to encourage them to stay. In the targeted approach the company tries to identify in advance customers who are likely to churn. We'll try to develop an algorithm to predict the churn score based on usage pattern. **

## Predictors in the data set
|Feature|Explanation|
|---------|-----------|
|State|Geographic location of the customer|
|Account Length|Length of time customer has been with the company|
|Area Code|Prefix of the phone number|
|Phone|Phone number|
|Int'l Plan|Customer has a plan for International calls?|
|VMail Plan|Customer has a VMail plan?|
|VMail Message|Number of VMail messages|
|Day Mins|Length of day-time calls|
|Day Calls|Number of day-time calls|
|Day Charge|Cost of day-time calls|
|Eve Mins|Length of evening calls|
|Eve Calls|Number of evening calls|
|Eve Charge|Cost of evening calls|
|Night Mins|Length of night-time calls|
|Night Calls|Number of night-time calls|
|Night Charge|Cost of night-time calls|
|Intl Mins|Length of international calls|
|Intl Calls|Number of international calls|
|Intl Charge|Cost of international calls|
|CustServ Calls|Number of calls made to Call Center|
|Churn?|Customer churned or not? (our label)|

## Step 1: Loading the data file
"""

df = read.csv("churn.txt")

head(df)

str(df)

"""## Step 2: Preprocessing and EDA
Assuming that features like state, area code and phone number won't have a predictive power on churn, we'll drop them. You may argue that state might play a role on churn but let's pretend that it doesn't. We'll insert the Boolean (True/False) equivalents for the categorical features Intl_Plan, VMail_Plan and Churn.
"""

library(dplyr)

# Drop columns by name
df <- df %>% select(-State, -Area.Code, -Phone)
# Replace 'True.' with TRUE (logical) in 'Churn' column
df <- df %>%
     rename(Churn = Churn.)
df$Churn <- df$Churn == "True."
df$Churn <- ifelse(df$Churn==TRUE,"YES","NO")
df$Churn <- as.factor(df$Churn)
# Replace 'yes'/'no' with TRUE/FALSE in 'Intl_Plan' and 'VMail_Plan'
yes_no_cols <- c("Int.l.Plan", "VMail.Plan")
df[yes_no_cols] <- lapply(df[yes_no_cols], function(x) x == "yes")

# Display the first 3 rows
head(df, 3)

"""At this point we'll explore the data by examining the cross correlation among attributes and how they vary in comparison to every other attribue in the data set. This may give us further insight with respect to the impact of all attributes to the prediction of churn."""

install.packages("corrplot")

library("corrplot")
cor_matrix <- round(cor(df[,c(-2,-3,-18,-19)]),2) #dropping non numerical columns
#cor_matrix

corrplot(cor_matrix)

"""Correlation matrix for Day_Mins vs Day_Charge above show us that (VMail_Plan,VMail_Message), (Day_Mins,Day_Charge),(Eve_Mins,Eve_Charge), (Night_Mins,Night_Charge) and (Intl_Mins, Intl_Charge) pairs are perfectly correlated. So we can drop one of the features in each pair."""

# Drop columns using dplyr's select()
df <- df %>%
  select(-Day.Charge, -Eve.Charge, -Night.Charge, -Intl.Charge)

# Get column names
col_names <- names(df)
col_names # Print out the column names

"""How is Churn distrbuted?"""

table(df$Churn)

table(df$Churn)/length(df$Churn)

install.packages("GGally")

library(GGally)
options(repr.plot.width = 14, repr.plot.height = 14)
df_to_plot = df[,c(-2,-3,-18,-19)]
ggpairs(df_to_plot,
        columns = 1:ncol(df_to_plot),  # Select all columns
        aes(color = Churn),   # Color by Churn
        upper = list(continuous = wrap("cor", size = 3)), # Correlation values
        lower = list(continuous = wrap("points", alpha = 0.5)), # Scatter plots
        diag = list(continuous = wrap("densityDiag", alpha = 0.5)))# Density plots

"""Out of 3333 instances, number of customers churning is 483, non-churning 2850. We have an unbalanced data set! We have to keep this in mind for the cross-validation phase and for the evaluation of the overall prediction accuracy.<br>

Here we look at some of the attributes that we think may be important:
"""

names(df)

# Day Mins Histogram
ggplot(df, aes(x = Day.Mins, fill = Churn)) +
  geom_histogram(alpha = 0.6, position = "identity",bins = 10) +
  ggtitle("Day.Mins for Churn and non-Churn") +
  theme_bw()

# Day_Mins Boxplot
ggplot(df, aes(x = Churn, y = Day.Mins)) +
  geom_boxplot(fill = "lightblue") +
  labs(title = "Day Minutes by Churn")

# Eve_Mins Boxplot
ggplot(df, aes(x = Churn, y = Eve.Mins)) +
  geom_boxplot(fill = "lightgreen") +
  labs(title = "Evening Minutes by Churn")

#Customer service calls

library(ggplot2)

# Create a contingency table
custserv_table <- as.data.frame(table(df$CustServ.Calls, df$Churn))
colnames(custserv_table) <- c("CustServ.Calls", "Churn", "Count")

# Plot grouped bar chart
ggplot(custserv_table, aes(x = CustServ.Calls, y = Count, fill = Churn)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  labs(title = "Customer Service Calls vs Churn", x = "CustServ Calls", y = "Count")

# international plan

library(ggplot2)

# Create a cross-tabulation and convert to dataframe
intlplan_table <- as.data.frame(table(df$Int.l.Plan, df$Churn))
colnames(intlplan_table) <- c("Int.l.Plan", "Churn", "Count")

# Plot stacked bar chart
ggplot(intlplan_table, aes(x = Int.l.Plan, y = Count, fill = Churn)) +
  geom_bar(stat = "identity", position = "stack") +
  labs(title = "International Plan vs Churn",
       x = "International Plan",
       y = "Count") +
  theme_minimal()

# international minutes and account length

# Day_Mins Boxplot
ggplot(df, aes(x = Churn, y = Intl.Mins)) +
  geom_boxplot(fill = "lightblue") +
  labs(title = "Day Minutes by Churn")

# Eve_Mins Boxplot
ggplot(df, aes(x = Churn, y = Eve.Mins)) +
  geom_boxplot(fill = "lightgreen") +
  labs(title = "Evening Minutes by Churn")

"""Plots above hint at a few things:
* Evening and Night time calls (or their duration) don't seem to contribute to churn.
* The length of the day-time calls, however, seems to have an impact on churn if it's longer than 250 minutes as is evident from the first plot above.
* Second plot supports this finding while the boxplot for the evening calls doesn't seem to change much for either class.
* The number of calls made to the call center seems to matter for 4 calls and above (third plot).
* In the fourth plot, it is evident that those customers with an International Plan tend to churn more (total duration of the calls doesn't seem to have mmuch effect).
* In the 5th plot, we see that a long Account_Length doesn't stop subscribers from churning.

## Step 3: Building the Model with Logistic Regression
In this step, we'll fit a Logistic Regression model to our data. We need to represent our dataframe as a matrix as expected by  the scikit module now. We convert the pandas dataframe into a numpy matrix (for both X and y) down below:
"""

install.packages("ROCR")
install.packages("caret")

library(caret)
# set random number seed for randomized partition
# different seed values will generate different partitions of the data
# Create stratified folds
indxTrain <- createDataPartition(y = df$Churn,
                                 p = 0.7,
                                 list = FALSE,
                                 groups = length(unique(df$Churn))) # stratified folds..

# Define training and testing sets
training <- df[indxTrain, ]
testing <- df[-indxTrain, ]

model = glm(Churn ~ ., data=training,family = binomial)
summary(model)

logregPredictProb <- predict(model, newdata = testing, type = "response")
logregPredictClass <- ifelse(logregPredictProb > 0.5, "YES", "NO")

# 3. Convert predicted classes to factor with same levels as the true values
logregPredictClass <- factor(logregPredictClass, levels = levels(testing$Churn))
# Now compute the confusion matrix correctly
confusionMatrix(logregPredictClass, testing$Churn, positive = "YES")

"""Our classification accuracy is no better than the "**Null Accuracy**", which was 85.5%."""

library(ROCR)
# data structure for constructing ROC and lift curves
pred <- prediction(logregPredictProb, testing$Churn)

# plot AUC
perAUC <- performance(pred,"tpr", "fpr")

# Calculate AUC
auc <- performance(pred, "auc")
auc <- unlist(slot(auc, "y.values"))

# Print AUC
print(paste("AUC:", auc))


plot(perAUC, main = paste("AUC:",auc))
abline(0,1)

"""## Step 4: Evaluation of the Model Accuracy

The model accuracy found earlier was 85.89% on the test set. Considering the unbalanced data set, which revealed proportions of 85.5% and 14.5% for non-churn and churn, respectively, this is no better than the null accuracy, which is the accuracy of the most naive model which predicts everything as "no-churn". So we're no better than this.

we need to approach this problem from a different angle.

### Breakdown of the cost:
What are the costs for my problem of mobile operator churn? The costs, of course, depend on the specific actions that the business takes. How about making some assumptions here. First, let's assign the true negatives (**TN**)the cost of **0TL**. My model essentially correctly identified a happy customer in this case, and I don’t need to do anything.

False negatives (**FN**) are the most problematic, because they incorrectly predict that a churning customer will stay. They  will lose the customer and will have to pay all the costs of acquiring a replacement customer, including foregone revenue, advertising costs, administrative costs, point of sale costs, and likely a phone hardware subsidy. For the purposes of this problem, let's assume the cost as **500TL**, which is a reasonable amount. This is the cost of false negatives (**FN**).

Finally, for customers that my model identifies as churning, I will assume a retention incentive in the amount of **100TL**. If the provider offered its subscriber a concession of this sort, the subscriber would probably think twice before leaving. This is the cost of both true positive (**TP**) and false positive (**FP**) outcomes. In the case of false positive (**FP**), the customer is happy, but the model mistakenly predicted churn. So we will “waste” the **100TL** concession. The service provider probably could have spent that **100TL** more effectively, but in the end they possibly increased the loyalty of an already loyal customer, so that’s not necessarily so bad.

**Here is the model for the cost function**:
$$Cost = 500TL * FN + 0TL * TN + 100TL * FP + 100TL * TP$$


The model predicts any input as "churn", i.e. as p(Y=1|X), whenever the probability is equal and above the threshold of 0.5 (50%). Now we will try to find the optimum threshold that minimizes the cost function we constructed above. For this, we'll compute the cost function for a range of cutoff values for the probability thresholds:
"""

# Required libraries
library(caret)
library(ggplot2)

# Custom cost function
costfunc <- function(conf_matrix) {
  TP <- conf_matrix[2, 2]
  TN <- conf_matrix[1, 1]
  FP <- conf_matrix[2, 1]
  FN <- conf_matrix[1, 2]
  cost <- 500 * FN + 0 * TN + 100 * FP + 100 * TP
  return(cost)
}

# Predict probabilities
y_pred_prob <- predict(model, testing, type = "response")

Xp <- c()
Yp <- c()

cat("Cutoff  Cost/customer (TL)   Accuracy\n")

# Loop over thresholds
for (cutoff in seq(0, 1, length.out = 20)) {
  y_pred_class <- ifelse(y_pred_prob > cutoff, "YES", "NO")
  y_pred_class <- factor(y_pred_class, levels = levels(testing$Churn))

  cm <- table(Predicted = y_pred_class, Actual = testing$Churn)
  cost <- costfunc(cm)/length(testing$Churn)
  accuracy <- mean(y_pred_class == testing$Churn)

  Xp <- c(Xp, cutoff)
  Yp <- c(Yp, cost)

  cat(sprintf('%4.2f   %6.2f                %5.3f\n', cutoff, cost, accuracy))
}

# Plotting
plot(Xp, Yp, type = "l", col = "blue", lwd = 2,
     xlab = "Threshold value for probability", ylab = "Cost per customer (TL)",
     main = "Cost Curve by Threshold")
abline(h = min(Yp), col = "red", lty = 2)

"""### Interpretation of the current approach:
Now we're ready to compare the financial outcomes of using vs. not using this model. We can treat not using an ML model as a simple strategy–a kind of primitive model. In other words, if the provider doesn’t use ML, they're assuming that everyone is loyal and not offering anyone any concessions. They’ll be making a false negative (**FN**) type of mistake 14.5% of the time. If they want to maintain their current pool of customers, this strategy will cost them **500TL x 0.145** or **72.5TL/customer**, on average.

If the provider uses the ML model with a calculated optimal threshold of $0.21$, overall accuracy will go down to **79%**, which is lower than what we had before (the one that doesn't use a model). But the overall cost of this strategy drops to around **50TL/customer**. This is substantially better than **72.5TL/customer**. It's a much better decision to deploy the ML model!

This approach gives the provider the ability to compare the performance of different strategies–including strategies that don’t involve ML – in clear financial terms. In this example, using a Machine Learning model has a **22.5TL/customer** advantage. If the costs and assumptions are accurate, for a hypothetical small mobile operator with only 100,000 customers this equals over **2M TL** in savings!
"""